theme: jekyll-theme-cayman
markdown: GFM
github:
  is_project_page: false

title: Rückenfit macht GLÜCKLICH!
email: britta@zeitlinger.de
description: >
  Brittas Online-Rückenfit-Kurse über Zoom

tags:
  - Kleine Gruppen
  - Kurse
  - Zoom
  - Online
  - Rückenfit

lang: de_DE
google_analytics: G-90DWF3T3YS

plugins:
  - jekyll-seo-tag
  - jekyll-theme-cayman
