theme: jekyll-theme-cayman
markdown: GFM
github:
  is_project_page: false

title: BEWEGUNG macht GLÜCKLICH!
email: britta@zeitlinger.de
description: >
  Brittas Online-Rückenfit-Kurse über Zoom
  
background: assets/background.jpg

lang: de_DE
google_analytics_id: G-90DWF3T3YS

plugins:
  - jekyll-analytics

jekyll_analytics:
  GoogleAnalytics:
    id: G-90DWF3T3YS
    anonymizeIp: false
